package com.shopsphere.controller;
import com.shopsphere.model.*; import com.shopsphere.repo.*; import com.shopsphere.security.*; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api") public class ApiController { private final UserRepository users; private final OrderRepository orders; private final BCryptPasswordEncoder enc; private final JwtFilter jwt; public ApiController(UserRepository u,OrderRepository o,BCryptPasswordEncoder e,JwtFilter j){users=u;orders=o;enc=e;jwt=j;}
record Register(String name,String email,String phone,String password){} record Login(String email,String password){} record Item(Long productId,String productName,int quantity,double price){} record Checkout(List<Item> items){}
@PostMapping("/auth/register") ResponseEntity<?> register(@RequestBody Register r){if(users.existsByEmail(r.email().toLowerCase()))return ResponseEntity.status(409).body(Map.of("message","Account already exists"));User u=new User();u.name=r.name();u.email=r.email().toLowerCase();u.phone=r.phone();u.passwordHash=enc.encode(r.password());users.save(u);return ResponseEntity.status(201).body(Map.of("message","Account created. Please login."));}
@PostMapping("/auth/login") ResponseEntity<?> login(@RequestBody Login r){var u=users.findByEmail(r.email().toLowerCase());if(u.isEmpty()||!enc.matches(r.password(),u.get().passwordHash))return ResponseEntity.status(401).body(Map.of("message","Invalid email or password"));return ResponseEntity.ok(Map.of("token",jwt.token(u.get().email,u.get().id),"name",u.get().name));}
@GetMapping("/products") Object products(){return List.of(Map.of("id",1,"name","Aurelia Headphones","price",12999,"category","Audio","emoji","🎧"),Map.of("id",2,"name","Noir Smartwatch","price",18999,"category","Wearables","emoji","⌚"),Map.of("id",3,"name","Luma Camera","price",45999,"category","Camera","emoji","📷"),Map.of("id",4,"name","Arc Mechanical Keyboard","price",8999,"category","Workspace","emoji","⌨️"),Map.of("id",5,"name","Halo Speaker","price",10999,"category","Audio","emoji","🔊"),Map.of("id",6,"name","Slate Tablet","price",32999,"category","Mobile","emoji","📱"));}
@PostMapping("/orders") Object checkout(@RequestBody Checkout x,Authentication a){Long uid=(Long)a.getDetails();User u=users.findById(uid).orElseThrow();Order o=new Order();o.user=u;o.totalAmount=x.items().stream().mapToDouble(i->i.price()*i.quantity()).sum();for(Item i:x.items())o.items.add(new OrderItem(i.productId(),i.productName(),i.quantity(),i.price()));return orders.save(o);}
@GetMapping("/orders") Object history(Authentication a){return orders.findByUserIdOrderByCreatedAtDesc((Long)a.getDetails());}
@GetMapping("/health") Object health(){return Map.of("status","UP");}
}
