server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shopsphere}
    username: ${DB_USER:shopsphere}
    password: ${DB_PASSWORD:shopsphere123}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
app:
  jwt-secret: ${JWT_SECRET:change-this-demo-secret-key-change-this-demo-secret-key}
